### ISSUE TITLE
Change opacity & color of clip selection tools

### ISSUE THREAD

**Issue by begna112** [TypesettingTools/Aegisub#1]
It would be really nice to be able to change the opacity and color of the clip selection lines and masked-area. Especially for anyone with any form of colorblindness, this can make the difference between usable and not. 

For example, being partially colorblind myself, these clip colors are nearly impossible for me to see which made it take infinitely longer. 

![aegisub64_2018-02-09_18-36-09](https://user-images.githubusercontent.com/10567958/38772579-ad633360-3fff-11e8-9675-b71b0b2822ca.png)

Ideally this would just be another setting in the "Colors" options page.

**Comment by CoffeeFlux** [comment]
I think this should be fairly easy to do; I'll take a look later this week.

**Comment by CoffeeFlux** [comment]
Resolved by https://github.com/TypesettingTools/Aegisub/commit/42b507f7038eeefb31db0055043d305fd137f8ad
