### ISSUE TITLE
Some letters of a font make the writing disappear

### ISSUE THREAD

**Issue by zFerry98** [TypesettingTools/Aegisub#101]
With a certain font, ON Aegisub ONLY, some letters are not loaded / bugged and everything you type after is not seen.
It only happens on Aegisub, SubtitleEdit and Photoshop use the font smoothly.

Bugged letter: WOP SHK M
Aegisub: 8975 - Master8d77da3
Windows 10 x64
Files: https://mega.nz/folder/A0tlDCiZ#XHUCp1vb-w-stp7FC7o5SA

## Original Text (O bugged): 
![image](https://user-images.githubusercontent.com/17975351/105041091-dd3d2980-5a62-11eb-8162-a70c0e3bd311.png)

## Test 1 (Aegisub):
![image](https://user-images.githubusercontent.com/17975351/105041241-078ee700-5a63-11eb-8f9b-aca37bd5b4c0.png)

## Test 2 (SubtitleEdit):
![image](https://user-images.githubusercontent.com/17975351/105041309-1d9ca780-5a63-11eb-8267-d74055ba5452.png)

**Comment by petzku** [comment]
Are you using the `libass` or `CSRI/vsfilter_textsub` subtitle provider? The latter will often fail to render very complex glyphs, such as this type of "rugged" ones.

**Comment by zFerry98** [comment]
> Are you using the `libass` or `CSRI/vsfilter_textsub` subtitle provider? The latter will often fail to render very complex glyphs, such as this type of "rugged" ones.

I use a custom version of the VSFilter, however, a friend of mine using Aegisub "vanilla" (with the VSFilter built into aegi) gives the same problem. He was the one who told me about the bug, then I tried it and the same thing happened to me too although I use a more updated version.

My Ver: 
![image](https://user-images.githubusercontent.com/17975351/105080605-56537580-5a91-11eb-9d47-99e6ee4ed273.png).

My xy-filter: https://github.com/pinterf/xy-VSFilter/releases

**Comment by Myaamori** [comment]
If it works with libass, it sounds like it's the VSFilter issue petzku mentioned. Have you tried seeing if it works in a VSFilter-based video player? If not, the issue is probably unrelated to Aegisub.

**Comment by zFerry98** [comment]
> If it works with libass, it sounds like it's the VSFilter issue petzku mentioned. Have you tried seeing if it works in a VSFilter-based video player? If not, the issue is probably unrelated to Aegisub.

Libass works. 

![image](https://user-images.githubusercontent.com/17975351/105097143-675bb100-5aa8-11eb-9796-31b4f6ffd0f9.png)
(dummy video, strike the blood II ep1) xy-filter mod

😥 no way to fix (latest version of xy-vsfilter 2018... developer ☠☠☠)
