### ISSUE TITLE
Windows MSVC builds crash on startup

### ISSUE THREAD

**Issue by dixie-flatliner** [TypesettingTools/Aegisub#103]
Per the title, attempting to launch a binary from the CI spawns an error dialog stating "The procedure entry point hb_blob_create could not be located in the dynamic link library C:\Program Files\Aegisub\aegisub.exe"; clicking OK or closing it terminates the process. The GUI is not loaded, no log/crashdump files are created, and if it's the first launch after a fresh install no AppData directory is created either.

Tested with the latest commit and [417ba4f](https://github.com/TypesettingTools/Aegisub/actions/runs/475303375).

Can't provide any more info as I am now, sorry. (Other than that Google points to the error message having something to do with HarfBuzz.)

**Comment by CoffeeFlux** [comment]
It sounds like the ci builds are using system harfbuzz, which is not great. It should be statically linking everything.

**Comment by inkydragon** [comment]
Test [7e9c7d7](https://github.com/TypesettingTools/Aegisub/actions/runs/870063438) in clean windows sandbox (Win10+2004).

It works well.

**Comment by CoffeeFlux** [comment]
This was fixed with https://github.com/TypesettingTools/Aegisub/commit/0f95589d0accea9bd33e029e82bda089f32206f3, so closing.
