### ISSUE TITLE
XDG Base Directory Specification on linux

### ISSUE THREAD

**Issue by polirritmico** [TypesettingTools/Aegisub#110]
Aegisub uses ~/.aegisub for configuration, logs, cache files, etc. instead of using XDG compliant directories, e.g. $XDG_CONFIG_HOME, $XDG_CACHE_HOME, and $XDG_DATA_HOME.

Could Aegisub implement the XDG Base Directory Specification standard for Linux?:
[https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

Regards.

**Comment by polirritmico** [comment]
Think I post this on the wrong github: repost on https://github.com/Aegisub/Aegisub/issues/new

**Comment by barraIhsan** [comment]
> Think I post this on the wrong github: repost on https://github.com/Aegisub/Aegisub/issues/new

From 2025 here, this is now the official repo. Anyway, #264 supposed to resolve this issue, and I hope I can finally clean my HOME dir
