### ISSUE TITLE
apply karaoke template error

### ISSUE THREAD

**Issue by lyturn** [TypesettingTools/Aegisub#141]
error code:

Runtime error in template code: Expected 1 arguments, got 2 Code producing error: ci = { 0,0 }; cn = _G.unicode.len(orgline.text_stripped:gsub(" ",""))

**Comment by arch1t3cht** [comment]
The real reason for this error is that argument checking was added to the Lua functions provided by Aegisub in https://github.com/Aegisub/Aegisub/commit/e3c60514cd1b5fcffa53891622ef48cd288f64c7 . This change happened on Aegisub/Aegisub it just wasn't part of the 3.2.2 release. That is why `string.gsub` returning two values causes an error here.

As mentioned above, this error can easily be worked around by adding an additional pair of parentheses around the `gsub` call.
