### ISSUE TITLE
[macOS] App icon is corrupted and does not display correctly at certain small sizes

### ISSUE THREAD

**Issue by shinra-electric** [TypesettingTools/Aegisub#144]
The app icon is fine at certain sizes, but when displayed in column view or a few other small sizes it is corrupted. 

![Screenshot 2021-11-14 at 17 47 42](https://user-images.githubusercontent.com/50119606/141693807-6293c9d0-7302-4950-bf88-51b6bf87cb45.png)

**Comment by shinra-electric** [comment]
Temporary workaround: 

- Right-click on the app and select Show Package Content
- in Contents/Resources drag Aegisub.icns outside the app (hold down option when dragging to make a copy)
- Open Aegisub.icns in Preview
- In the Thumbnail view, drag the top image (largest) to the desktop. It will save as a .tiff file
- Get info on the Aegisub app 
- Drag the Tiff file over the corrupted icon

**Comment by TheOneric** [comment]
likely related: https://github.com/Aegisub/Aegisub/pull/128 and https://github.com/wangqr/Aegisub/commit/e7b64aa7414c821b620e049f3a0ed70fd9d2be4c

**Comment by shinra-electric** [comment]
Yes, I'd say that commit from Madds fixes it
