### ISSUE TITLE
meson cannot find boost

### ISSUE THREAD

**Issue by milahu** [TypesettingTools/Aegisub#151]
probably an upstream bug ...

error was

```
Run-time dependency Boost (missing: chrono, filesystem, locale, regex, system, thread) found: NO 
```

workaround with this instead of `dependency('boost' ...`

```meson
boost_dep = [
    cc.find_library('boost_system'),
    cc.find_library('boost_chrono'),
    cc.find_library('boost_filesystem'),
    cc.find_library('boost_thread'),
    cc.find_library('boost_locale'),
    cc.find_library('boost_regex'),
]
```

problem is the `modules` parameter for `dependency('boost' ...`
when i remove it, boost is found, but i get link errors like

```
undefined reference to `boost::filesystem::path::operator/=
```

related but not helpful https://unix.stackexchange.com/questions/408963/meson-doesnt-find-the-boost-libraries

**Comment by FichteFoll** [comment]
What's your OS and meson version?

**Comment by eli-schwartz** [comment]
> i guess that meson's `dependency('boost'` is looking for pkg-config files (*.pc)

Boost upstream doesn't provide .pc files (sad, but they seem to irrationally dislike the idea).

Instead, Meson includes a custom dependency lookup, defined here: https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/boost.py

You may need to define `$BOOST_ROOT` for that to work.

**Comment by milahu** [comment]
so meson seems to dislike the idea of a cmake lookup https://github.com/mesonbuild/meson/issues/8801

closing as "has workaround"

thanks : )
