### ISSUE TITLE
can not install VsfilterMod

### ISSUE THREAD

**Issue by datcamap** [TypesettingTools/Aegisub#152]
### I got VSFilterMod.dll in the csri folder

![image](https://user-images.githubusercontent.com/48880635/157186819-83bccb49-bfb1-473d-8dd6-d82775a63e96.png)

### But it doesn't appear in the setting window

![image](https://user-images.githubusercontent.com/48880635/157186799-cedaa7e9-009d-4af2-bcae-1ede2b3fb6a2.png)

**Comment by Masaiki** [comment]
too old, this will work
https://github.com/sorayuki/VSFilterMod
