### ISSUE TITLE
fail to meson build on windows 11

### ISSUE THREAD

**Issue by huangweicong112** [TypesettingTools/Aegisub#196]
This is my first time to build Aegisub on my windows, and I have already install all the requirements. But when I am trying to meson build it, it faild.
![微信图片_20240207181226](https://github.com/TypesettingTools/Aegisub/assets/3403316/ffb2e72a-1fc0-4600-b513-71a1c53ae286)
I don't know what the problem is and need help.
Thanks

**Comment by arch1t3cht** [comment]
You need to pass `-Dharfbuzz:icu=disabled` with the meson configuration. This is fairly new so it's not yet described in the README. (In general, you can follow [the github workflow](https://github.com/TypesettingTools/Aegisub/blob/master/.github/workflows/ci.yml) when running into issues while compiling. That's usually more up-to-date than the README.)
