### ISSUE TITLE
opening subtitles will open an empty program: 3.4.0

### ISSUE THREAD

**Issue by AdventurerRussia** [TypesettingTools/Aegisub#219]
video
https://disk.yandex.ru/i/_xgeiAsF2hWIRg

I deleted the settings of the previous program from the user's folder.

Выпуск	Windows 11 Pro
Версия	24H2
Дата установки	‎16.‎06.‎2024
Сборка ОС	26100.2454

**Comment by AdventurerRussia** [comment]
we found that if there are Russian letters in the path to the file, that is, Cyrillic, then the file does not open,

**Comment by arch1t3cht** [comment]
Does opening the subtitles in Aegisub via File > Open work? Does opening the subtitles via "Open With" from the Explorer work? Did dragging those subtitles into Aegisub work on 3.2.2?

**Comment by AdventurerRussia** [comment]
> Does opening the subtitles in Aegisub via File > Open work? Does opening the subtitles via "Open With" from the Explorer work? Did dragging those subtitles into Aegisub work on 3.2.2?



in 3.4.0 version, if you open via (file-open new subtitles), then the subtitles open. 
--
subtitle dragging works fine in version 3.2.2, I downloaded the portable version. Everything is fine in it.
--
again, the problem with not opening subtitles directly is observed if they are in folders with Russian characters in their names

**Comment by 0tkl** [comment]
I can reproduce the bug.

Furthermore, in File Explorer, right click on the .ass file, select "Open With > Aegisub" in the context menu, results in a blank Aegisub interface (behaves like doesn't opening any file).

**Comment by geezeng** [comment]
I also encountered the same problem.
