### ISSUE TITLE
Videos no display

### ISSUE THREAD

**Issue by Qxqxq777** [TypesettingTools/Aegisub#235]
I recently installed Aegisub, starting with version 3.4.0. I used it for an evening, and everything seemed to work perfectly without any issues. The next day, I wanted to continue, but no video was displayed in the integrated player, although the audio worked just fine.

At first, I thought the issue might be related to the format/codec of my video not being supported properly (.MKV x265). So, I tried with a random video from the internet in MP4 x264 format, but once again, it didn’t display.

I uninstalled and reinstalled Aegisub several times with different versions (3.2.2, arch1t3cht), tried countless different videos, but NONE of them displayed. (I tested both the .exe and portable versions.)

I went into the advanced video settings, and FFmpegSource was correctly selected. I also tried BestSource and VapourSynth, but the issue persisted.

My theory is that the problem might not come directly from Aegisub but rather from something on my PC that’s interfering with it. What surprises me is that the .exe worked perfectly at first…

I feel like I’ve tried everything. Does anyone know how to fix this issue?
PS: In the attached example, it’s the arch1t3cht version. I installed it fully and didn’t change any settings.

(https://youtu.be/OwUohaRALaA)

**Comment by EL-File4138** [comment]
The video is currently not helpful. Could you copy the content in Help -> Log window after you open a video that cannot display, and paste it here (or other Pastebin services)?

**Comment by Qxqxq777** [comment]
After extensive searching, I’ve finally found a solution to my problem.
I’m using a laptop with an APU, and due to energy optimization, my dedicated GPU doesn’t activate for light tasks. However, it seems that the APU alone is not compatible with Aegisub. I forced my laptop to use the dedicated GPU, and now everything works perfectly.

This also explains why Aegisub worked for me the first time: I must have had a game like Valorant running in the background, which automatically triggered the dedicated GPU.

I’m not sure if this issue is specific to my APU or if it applies to all APUs, but if it’s the latter, it would be helpful to mention it somewhere.
