### ISSUE TITLE
v3.4.0: please add tarball with git_version.h

### ISSUE THREAD

**Issue by darealshinji** [TypesettingTools/Aegisub#244]
The source tarball generated by Github is missing `git_version.h` and the script `tools/version.sh` cannot be used because the `.git` repository is missing.
Can you please add a tarball with the correct `git_version.h` file to the release section?

By the way, this is the generated file from the v3.4.0 release branch:
``` c
#define BUILD_GIT_VERSION_NUMBER 9366
#define BUILD_GIT_VERSION_STRING "9366-(unnamed branch)-b0fc74109"
#define TAGGED_RELEASE 0
#define INSTALLER_VERSION "0.0.0"
#define RESOURCE_BASE_VERSION 0, 0, 0
```

But I assume it should be something like this?
``` c
#define BUILD_GIT_VERSION_NUMBER 9366
#define BUILD_GIT_VERSION_STRING "9366-v3.4.0-b0fc74109"
#define TAGGED_RELEASE 0
#define INSTALLER_VERSION "3.4.0"
#define RESOURCE_BASE_VERSION 3, 4, 0
```

**Comment by arch1t3cht** [comment]
Yes, I am currently working on this, see the `meson_dist` branch. It just needs another PR to be merged first before I can work out how to upload the tarballs from the CI.

**Comment by arch1t3cht** [comment]
Done in #251.
