### ISSUE TITLE
the absence of English lines in the ru.po file so that these lines can be translated later.

### ISSUE THREAD

**Issue by AdventurerRussia** [TypesettingTools/Aegisub#253]
the lines with this text are missing from the ru.po file.
![image](https://github.com/user-attachments/assets/dcf33bc8-20eb-4528-8a6e-1918dd3a8e37)
![image](https://github.com/user-attachments/assets/00a87091-70d5-4574-9a5e-a53cdc33c9a4)
![image](https://github.com/user-attachments/assets/6d018529-febf-4351-abcc-a13d40b19164)
![image](https://github.com/user-attachments/assets/1fe5f221-1fc9-4358-bf6b-fce4ca0f6af8)
![image](https://github.com/user-attachments/assets/55a66c59-9f2e-4224-822a-1274357607e4)
![image](https://github.com/user-attachments/assets/a52789b4-e8e3-4a1d-b1f7-1e4a4b7e03ab)
and also, many icons when hovered over also do not have a translation, since these lines are not in the ru.po file.
![image](https://github.com/user-attachments/assets/c0960087-6474-44d4-a5e9-d56c378e812f)
![image](https://github.com/user-attachments/assets/ed65557b-345b-433c-990f-809a94f6e2e5)

as well as some menu items.
![image](https://github.com/user-attachments/assets/5791e692-8389-4887-9df4-9286f7b0b80d)
![image](https://github.com/user-attachments/assets/17c138ec-d058-458b-958e-760f4f7f9979)

**Comment by AdventurerRussia** [comment]
about the bug that I sent earlier.
I checked the build using this link https://github.com/TypesettingTools/Aegisub/actions/runs/12551174817
now everything works fine when subtitles are in folders with Russian characters.

**Comment by arch1t3cht** [comment]
The strings not appearing in the .po file can be fixed by updating the .po file with the aegisub.pot file, e.g. with `msgmerge aegisub.pot -U ru.po`.

**Comment by AdventurerRussia** [comment]
> The strings not appearing in the .po file can be fixed by updating the .po file with the aegisub.pot file, e.g. with `msgmerge aegisub.pot -U ru.po`.

I have installed GNU gettext and I applied your command, it just created a file aegisub.pot~ no different from aegisub.pot

It looks like I'm doing something wrong. ¯\_(ツ)_/¯

**Comment by arch1t3cht** [comment]
Ah, indeed, I got the order wrong. It should be `msgmerge ru.po aegisub.pot -U`.

**Comment by AdventurerRussia** [comment]
> Ah, indeed, I got the order wrong. It should be `msgmerge ru.po aegisub.pot -U`.

It worked, thanks
[ru.zip](https://github.com/user-attachments/files/18282399/ru.zip)

**Comment by AdventurerRussia** [comment]
You can add this file to the repository, right?
