### ISSUE TITLE
Support other Keyframe formats

### ISSUE THREAD

**Issue by begna112** [TypesettingTools/Aegisub#4]
Currently aegisub only seems to support ffms2 generated keyframes or those created by scxvid+AVS which is an aging software/library/technology. 

Example of scxvid:
```
# XviD 2pass stat file (core version 1.4.-127)
# Please do not modify this file

i 2 8160 0 0 22890 22594
p 2 0 0 8160 1102 1102
p 2 0 34 8126 1136 1136
p 2 0 0 8160 1102 1102
p 2 0 0 8160 1102 1102
p 2 0 0 8160 1102 1102
p 2 0 0 8160 1102 1102
p 2 0 0 8160 1102 1102
p 2 0 0 8160 1102 1102
p 2 9 110 8041 3794 1242
p 2 7171 986 3 37443 26575
p 2 5303 2852 5 52769 27249
p 2 2988 5170 2 72779 26249
p 2 2503 5657 0 84756 27368
p 2 1909 6251 0 90766 25363
p 2 1730 6430 0 101239 25896
```

Could other keyframe formats be supported as well? For example ones created with VapourSynth and WWXD (https://github.com/Irrational-Encoding-Wizardry/kagefunc/blob/master/kagefunc.py#L112):

Example of WWXD keyframes:
```
0 I -1
75 I -1
127 I -1
224 I -1
412 I -1
572 I -1
653 I -1
728 I -1
796 I -1
930 I -1
979 I -1
```

The major difference is that scxvid keyframes seem to rely on the line number to indicate the i-frames (line# - 4 actually) whereas the wwxd ones actually output the frame number to the file.

Attaching full file examples
[SCXvid](https://github.com/TypesettingTools/Aegisub/files/1976326/Erai-raws.Full.Metal.Panic.Invisible.Victory.-.04.1080p._keyframes.log)
[WWXD+VS](https://github.com/TypesettingTools/Aegisub/files/1976327/keyframes.txt)

While not exactly core to Aegisub's functionality, it would certainly help users who also want to stop using Avisynth and scxvid.

It's worth nothing that the format used in the VS get_keyframes function linked above are in the format of x264 and x265's qpfile, so they aren't just in an arbitrary format: http://www.chaneru.com/Roku/HLS/X264_Settings.htm#qpfile http://x265.readthedocs.io/en/default/cli.html#cmdoption-qpfile

Additionally, basing it on x264/x265's qpfile format allows for other scene detection filters to be used in the future and use x264/x265's much more readable format.

**Comment by CoffeeFlux** [comment]
Change merged to kagefunc, so now I just have to add it to Aegisub

**Comment by CoffeeFlux** [comment]
Done and done
