### ISSUE TITLE
Small tweak to build on Linux Mint 19

### ISSUE THREAD

**Issue by HyperTesto** [TypesettingTools/Aegisub#57]
Hi everyone, 
i came across this repo looking for a more up to date fork of  Aegisub. You guys are awesome!

I've successfully built everything from the latest commit following the instructions on [anilom9's fork](https://github.com/aniolm9/Aegisub) but i encountered a small problem while compiling.

I had an error on file `src/libresrc/Makefile` at line 13. Replacing `$(TOP)$(BIN_LUA)` with `lua` made the build process work correctly.

I'm not a C/C++ guy so i don't know it that was intended or if i was missing something, so i'm just reporting it.

I also wanted to ask if this fork is intended to be a new official Aegi mantained fork (considering the pending issues/mr) and if you have a irc/Discord to get in touch.

Thank you guys!

**Comment by CoffeeFlux** [comment]
Yeah, that particular makefile issue is known and I need to fix it ASAP, I've just been busy. I attempted to fix things on new OSX versions and broke linux unintentionally in the process. A bunch of people have reported this so I'll try to get to it tonight, I've put it off for way too long.

There is in fact a Discord: https://discordapp.com/invite/AZaVyPr

There's a long-standing issue with newer versions of ffms2 that affects builds from this fork that I still need to finish my fix for, and then hopefully I'll be ready to put out a stable.

**Comment by HyperTesto** [comment]
Wow, fast answer! Thank you man!

**Comment by CoffeeFlux** [comment]
Fixed in d9bd7def0bb96c13295878ac567a3f6cd86e360f
