### ISSUE TITLE
Bug in very new version of Aegisub!!

### ISSUE THREAD

**Issue by NoNameUserDev** [TypesettingTools/Aegisub#67]
Hi! Sorry for my English in advance :)
In a very new version, 8975 build, that I know, there are bug related to videoframe or maybe audio.
When I opened a video and played his, I heard a dot-dot (how I can explain this?? a fragmentary audio? that has a noise and dotted) audio, which is weird. Therefore the correct timed sub file shows as missed, desynchronized to about 200 ms (or I could be wrong) sub.
I downloaded from https://thevacuumof.space/builds
And right away ask my second question :)
Is there a new version, newer than 8975?
Thank you all in advance!

**Comment by asakurato** [comment]
[aegisub64.zip](https://github.com/TypesettingTools/Aegisub/files/4374606/aegisub64.zip)
If you are on latest version, get this .exe and replace the existing one. It should fix the audio issues.

**Comment by NoNameUserDev** [comment]
@asakurato Hi! Thank you for response!
Let see... Wow! this is a 8992 build?! Just one question! Where did you get this?

**Comment by NoNameUserDev** [comment]
@asakurato Thank you very much! You saved me! Looks like that bug fixed in this build 8992.
Now I have restored my hope for new versions. I have a habit looking for new versions )
And I want to know where I should to get a newer versions :) I hope you will share a link
あざっす！

**Comment by FichteFoll** [comment]
It's a hotfix-like pre-release kind of thing, because the build system(s) are a mess currently and it's still rather painful to actually do a proper build on non-Linux systems.

**Comment by NoNameUserDev** [comment]
@FichteFoll Hi! I think I understand. This build (8992) must have compiled by him, right? If so, even I can compile my build? But it must be super difficult.

**Comment by FichteFoll** [comment]
Well, yes, in theory you could, but I have no idea how.
