### ISSUE TITLE
Outdated ffmpeg

### ISSUE THREAD

**Issue by NoNameUserDev** [TypesettingTools/Aegisub#75]
Hello everyone! Is there any way to update the ffmpeg, without rebuilding the Aegisub, like copying the new build of the ffmpeg.exe into the Aegisub folder? The reason I'm asking about this is that I couldn't open a certain mkv video with, appears to be, a new encoding parameters. But I can open without any problems in any video player...

**Comment by CoffeeFlux** [comment]
Resolved with Meson.
