### ISSUE TITLE
Feature Request: Separate Default Lead-Out from TPP Lead-Out

### ISSUE THREAD

**Issue by skiddiks** [TypesettingTools/Aegisub#8]
Current behavior: changing the value for lead-out in TPP also changes the default lead-out used for the lead-out hotkey. 

Requested behavior: Changing the lead-out value in tpp does not change the default lead-out. 

Use case: I like using a 380ms for my default lead-out. Let's say I get a pre-timed script that I want to make minor adjustments to. If I add 100ms lead-out with tpp, I now need to go to options to revert my default lead-out to 380ms. Separating the variables will fix this issue. Keeping them tied together has no upside I can think of.

Also, as I type this out, I realize this should also be applied to lead-in, but I'm too lazy to change what I've typed, so pretend I did ;)

**Comment by CoffeeFlux** [comment]
Resolved by https://github.com/TypesettingTools/Aegisub/commit/26ccf0b8e5374973b3a5edfe2bd958a1a2040da1
