### ISSUE TITLE
meson: prevent git_version.h from being regenerated every build

### ISSUE THREAD

**Issue by CoffeeFlux** [TypesettingTools/Aegisub#80]
This in turn forces files that depend on it to constantly rebuild, slowing down development significantly.

**Comment by Myaamori** [comment]
I've confirmed that this code works, though it's perhaps not the prettiest

```bash
if test -f "${version_h_path}"; then
  old_version="$(sed -rn 's/^#define BUILD_GIT_VERSION_STRING "([^"]+)"$/\1/p' "${version_h_path}")"
  if test "x$old_version" = "x$git_version_str"; then
    echo "git revision unchanged; skip generating git_version.h"
    exit 0
  fi
fi
```

There's also this code which is already present in `version.sh` which could be repurposed to extract `BUILD_GIT_VERSION_STRING` regardless of whether we are in a git directory or not, but it's currently broken - looks like it needs to be moved into its own function for the returns and exports(?) to work? (Or just remove the exports and returns if we don't mind the positional arguments being overridden by `set`.)

```bash
if ! test -d "${srcdir}/.git"; then
  if test -f "${version_h_path}"; then
    while read line; do
      set -- $line
      export $2=$(echo $3 | sed 's/"//g')
    done < "${version_h_path}"
    if test x$BUILD_GIT_VERSION_NUMBER != x -a x$BUILD_GIT_VERSION_STRING != x; then
      export VERSION_SOURCE="from cached git_version.h"
      return 0
    else
      echo "invalid git_version.h"
      exit 2
    fi
  else
    echo "git repo not found and no cached git_version.h"
    exit 2
  fi
fi
```

**Comment by CoffeeFlux** [comment]
Fixed in https://github.com/TypesettingTools/Aegisub/commit/aa81ea193a1ce9b4420d5fd60d703058359df55f
