### ISSUE TITLE
meson: patch ffms2 to disable audio gap filling

### ISSUE THREAD

**Issue by CoffeeFlux** [TypesettingTools/Aegisub#98]

**Comment by inkydragon** [comment]
Does this issue really matter? What will happen if we don't fix this.

**Comment by CoffeeFlux** [comment]
It does, unfortunately. This bug is a huge show-stopper for a lot of people, especially because it's not something they're likely to notice until they've already timed a large portion of the episode.

On certain videos the ffms2 gap-filling code overcorrects and the video timing will be subtly off, and it will get worse the longer the video plays. This means at playback the timing seems fine at first but progressively decays until it can be off by multiple seconds.

I'll also take a look at your PR in the next couple days—sorry for the delay, I've been out of town.

**Comment by inkydragon** [comment]
Relax and review the pull request at your own pace.

I want to know how to reproduce the problem.

According to my understanding, the problem is that Making subtitles in AEG work fine, but when subtitles are loaded with other players, the subtitle and the video is out of sync
